service: slack-chat
frameworkVersion: '3'

# Load environment variables from .env files (default: false)
useDotenv: true

provider:
  name: aws
  # Default stage (default: dev)
  stage: dev
  # Default region (default: us-east-1)
  region: ap-northeast-1
  # The AWS profile to use to deploy (default: "default" profile)
  # profile: default

  # Lambda Global Settings
  runtime: python3.12
  # Default memory size for functions (default: 1024MB)
  memorySize: 1536
  # Duration for CloudWatch log retention (default: forever).
  # Can be overridden for each function separately inside the functions block, see below on page.
  logRetentionInDays: 5
  # Use function versioning (enabled by default)
  versionFunctions: false
  # Processor architecture: 'x86_64' or 'arm64' via Graviton2 (default: x86_64)
  architecture: arm64

constructs:
  jobs:
    type: queue
    worker:
      handler: handler_consumer.lambda_handler
      environment:
        MODEL: ${env:MODEL}
        OPENAI_API_KEY: ${env:OPENAI_API_KEY}
        SLACK_TOKEN: ${env:SLACK_TOKEN}
        STREAM: ${env:STREAM}
      package:
        patterns:
        - 'handler_consumer.py'
        - 'models/**'
      timeout: 300
      maximumRetryAttempts: 0
      layers:
      - { Ref: PythonRequirementsLambdaLayer } # requirements.txt로 만든 layer

functions:
  producer:
    handler: handler_producer.lambda_handler
    events:
    - httpApi:
        method: any
        path: /
    environment:
      QUEUE_URL: ${construct:jobs.queueUrl}
    package:
      patterns:
      - 'handler_producer.py'
    maximumRetryAttempts: 0

plugins:
- serverless-lift
- serverless-python-requirements

package:
  individually: true
  patterns:
  - '!**'

custom:
  pythonRequirements:
    useDownloadCache: true
    useStaticCache: true
    layer:
      name: slackGPT
      description: Python requirements lambda layer
      compatibleRuntimes:
      - python3.12
      licenseInfo: GPLv3
      allowedAccounts:
      - '*'
